FROM public.ecr.aws/lambda/python:3.8

RUN mkdir /lam
COPY ./docker/requirements.txt /lam/requirements.txt
RUN pip3 install -r /lam/requirements.txt --target "${LAMBDA_TASK_ROOT}"
COPY . ${LAMBDA_TASK_ROOT}

CMD ["lambda_func.addNums"]
